dist: xenial
sudo: false

branches:
  only:
    - master

language: scala
scala:
  - 2.12.4

cache:
  directories:
    - $HOME/.ivy2

addons:
  apt:
    packages:
      # Debian package build
      - dpkg
      - dpkg-sig
      - dpkg-dev
      - lintian
      - fakeroot

script:
  - cd compiler
  - export GIT_COMMIT=$(git log -1 --format=%h)
  - export GIT_DATE_ISO=$(TZ=UTC git log -1 --date=iso-strict-local --format=%cd)
  - export GIT_DATE=$(TZ=UTC git log -1 --date=format-local:%Y%m%d.%H%M%S --format=%cd)
  - export KAITAI_STRUCT_VERSION=0.11-SNAPSHOT${GIT_DATE}.${GIT_COMMIT}
  - sbt compile compilerJVM/stage fastOptJS buildNpmJsFile buildNpmPackage compilerJVM/debian:packageBin compilerJVM/universal:packageBin
  - ./publish_deb_to_cloudsmith.sh
  - ../trigger-kaitai_struct_python_docker
  - ./publish_js_to_npm.sh && ../trigger-kaitai_struct_webide
  - cd ../tests
  - ./translator-tests || true
  - ./build-formats
  - ./push_artifacts/git_config_kaitai_bot
  - ./push_artifacts/publish
      -o kaitai-io
      -r ci_targets
      -m "Regen $TRAVIS_BRANCH kaitai-io/kaitai_struct@$TRAVIS_COMMIT"
      --
      --exclude=.git
      --exclude=.travis.yml
      compiled

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c6bd60df4d171f9d3789
